### ISSUE TITLE
Ежедневная награда

### ISSUE THREAD

**Issue by mainiken** [Mffff4/qlyukerbot#1]
Привет, есть возможность добавить функционал что бы забирало ежедневную награду, там очень хорошая сумма выходит. 

Спасибо!

**Comment by Mffff4** [comment]
> Привет, есть возможность добавить функционал что бы забирало ежедневную награду, там очень хорошая сумма выходит. 
> 
> 
> 
> Спасибо!

Привет. 
В процессе 🤝

**Comment by Mffff4** [comment]
Добавил сбор ежедневных наград.
Обнови tapper.py.

Если будут баги - пиши.

**Comment by mainiken** [comment]
Спасибо! Все ок!
