### ISSUE TITLE
Перестали работать тапы

### ISSUE THREAD

**Issue by edik007** [Mffff4/qlyukerbot#3]
Софт обновил только что.

> GV1 | Account data refreshed. Current coins: 208257839, Energy: 6000/6000   
> GV1 | Successfully logged in.                                               
> NS1 | Failed to send taps                                                   
> KV1 | Failed to send taps                                                   
> AM1 | Failed to send taps                                                   
> SS1 | Failed to send taps                                                   
> DM1 | Failed to send taps                                                   
> JC1 | Failed to send taps                                                   
> EP1 | Failed to send taps                                                   
> NS1 | ClientResponseError during send_taps: Status=403, Message=Forbidden,  
> Response=No response body                                                   
> NS1 | send_taps FAILED: Status=403, Response=Неверные данные                
> KV1 | ClientResponseError during send_taps: Status=403, Message=Forbidden,  
> Response=No response body                                                   
> KV1 | send_taps FAILED: Status=403, Response=Неверные данные                
> KV1 | Failed to claim daily reward.                                         
> KV1 | ClientResponseError during claim_daily_reward: Status=403,            
> Message=Forbidden, Response=No response body                                
> KV1 | claim_daily_reward FAILED: Status=403, Response=Неверные данные       
> NS1 | Failed to claim daily reward.                                         
> NS1 | ClientResponseError during claim_daily_reward: Status=403,            
> Message=Forbidden, Response=No response body                                
> NS1 | claim_daily_reward FAILED: Status=403, Response=Неверные данные       
> AM1 | ClientResponseError during send_taps: Status=403, Message=Forbidden,  
> Response=No response body                                                   
> AM1 | send_taps FAILED: Status=403, Response=Неверные данные                
> AM1 | Failed to claim daily reward.                                         
> AM1 | ClientResponseError during claim_daily_reward: Status=403,            
> Message=Forbidden, Response=No response body                                
> AM1 | claim_daily_reward FAILED: Status=403, Response=Неверные данные       
> NS1 | Sending 29 taps. Energy before tap: 6000                              
> NS1 | Finished attempting tasks. Will try again in 8 hours.                 
>

**Comment by Mffff4** [comment]
Пофиксил.

**Comment by edik007** [comment]
Не пофиксилось, по прежнему:

```
AM1 | ClientResponseError during send_taps: Status=403, Message=Forbidden,
Response=No response body
AM1 | send_taps FAILED: Status=403, Response=Неверные данные
AM1 | Failed to claim daily reward.
AM1 | ClientResponseError during claim_daily_reward: Status=403,
Message=Forbidden, Response=No response body
AM1 | claim_daily_reward FAILED: Status=403, Response=Неверные данные
```

Скрипт работает через прокси. Но прокси работают. Все остальные команды выполняются.
